//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimKeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Event
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Time { get; set; }
        public string Place { get; set; }
        public string Description { get; set; }
    }
}
